modLoader = "javafml"
loaderVersion = "[38.0.17,)"
issueTrackerURL = "https://github.com/ajh123-development/better-cc/issues"
license = "GPL-3.0 License"

[[mods]]
modId = "better-cc"
version = "${version}"
displayName = "Better CC"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.better-cc]]
modId = "forge"
mandatory = true
versionRange = "[38.0.17,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better-cc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better-cc]]
modId = "architectury"
mandatory = true
versionRange = "[3.4.9,)"
ordering = "AFTER"
side = "BOTH"