modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/ajh123-development/better-cc/issues"
license = "GPL-3.0 License"

[[mods]]
modId = "better_cc"
version = "${version}"
displayName = "Better CC"
authors = "ajh123"
description = '''
Adds to computercraft!!
Adds, adds, and adds again!
'''
#logoFile = ""

[[dependencies.better-cc]]
modId = "forge"
mandatory = true
versionRange = "[40.1.25,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better-cc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better-cc]]
modId = "architectury"
mandatory = true
versionRange = "[3.4.9,)"
ordering = "AFTER"
side = "BOTH"